### ISSUE TITLE
Ask question "why would you like to meet"

### ISSUE THREAD

**Issue by gakshay** [gakshay/hookhook#5]
- [x] Show a ? (Question Mark) on User photo, clicking on which allows a user to write "Why he want to meet this person"
- [x] After a user writes the response for the above question, change the icon to Right Mark 
- [x] Use some color code to clearly discriminate between users (question answered vs not answered)

**Comment by guptapiyush** [comment]
1. Show the ? button permanently.
2. Show the RIGHT MARK button also permanently.

Since story is a crucial part. Creating a permanent visual cue would be really helpful.

When are we closing this?
![q pending or completed](https://cloud.githubusercontent.com/assets/3889292/7237080/e2049072-e74d-11e4-9e29-b9f49b038b88.png)

**Comment by sanjusoftware** [comment]
@guptapiyush added a question icon (see below tile ) to indicate the 'Story' part. It'll always be visible. 

![screen shot 2015-04-21 at 9 50 50 am](https://cloud.githubusercontent.com/assets/232573/7245632/1ab58124-e80c-11e4-827c-74225b817032.png)

Once the user story is given, the icon changes to following:

![screen shot 2015-04-21 at 9 51 04 am](https://cloud.githubusercontent.com/assets/232573/7245637/2bde7f0a-e80c-11e4-800d-bb333aa363d5.png)

this will be closed today.
